import tkinter as tk
from tkinter import messagebox
import oracledb

# Função para conectar ao banco de dados Oracle
def connect_to_db():
    try:
        connection = oracledb.connect(
            user="SYSTEM",
            password="senha",
            host="localhost",
            port=1521,
            service_name="XE"  # Substitua pelo nome do seu serviço
        )
        return connection
    except oracledb.DatabaseError as e:
        messagebox.showerror("Erro de Conexão", f"Erro ao conectar ao banco de dados: {e}")
        return None

# Função para criar a tabela TBL_FORNECEDORES
def create_table():
    try:
        connection = connect_to_db()
        if connection:
            cursor = connection.cursor()
            cursor.execute("""
            CREATE TABLE TBL_FORNECEDORES (
                ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME VARCHAR2(50) NOT NULL,
                DESCRICAO VARCHAR2(255),
                SETOR VARCHAR2(50),
                ENDERECO VARCHAR2(255),
                TELEFONE VARCHAR2(20),
                EMAIL VARCHAR2(100),
                SITE VARCHAR2(100)
            )
            """)
            connection.commit()
            messagebox.showinfo("Sucesso", "Tabela TBL_FORNECEDORES criada com sucesso!!")
    except oracledb.DatabaseError as e:
        messagebox.showerror("Erro de Banco de Dados", f"Erro ao criar tabela: {e}")
    finally:
        if connection:
            connection.close()

# Função para inserir fornecedor no banco de dados
def insert_supplier():
    nome = nome_entry.get()
    descricao = descricao_entry.get()
    setor = setor_entry.get()
    endereco = endereco_entry.get()
    telefone = telefone_entry.get()
    email = email_entry.get()
    site = site_entry.get()

    if not nome:
        messagebox.showerror("Erro de Validação", "Por favor, insira o nome do fornecedor.")
        return

    try:
        connection = connect_to_db()
        if connection:
            cursor = connection.cursor()

            # Query para inserir fornecedor
            query = """
            INSERT INTO TBL_FORNECEDORES (NOME, DESCRICAO, SETOR, ENDERECO, TELEFONE, EMAIL, SITE) 
            VALUES (:nome, :descricao, :setor, :endereco, :telefone, :email, :site)
            """
            cursor.execute(query, {
                "nome": nome,
                "descricao": descricao,
                "setor": setor,
                "endereco": endereco,
                "telefone": telefone,
                "email": email,
                "site": site
            })
            connection.commit()

            messagebox.showinfo("Sucesso", "Fornecedor cadastrado com sucesso!!")

            # Limpar os campos após o cadastro
            nome_entry.delete(0, tk.END)
            descricao_entry.delete(0, tk.END)
            setor_entry.delete(0, tk.END)
            endereco_entry.delete(0, tk.END)
            telefone_entry.delete(0, tk.END)
            email_entry.delete(0, tk.END)
            site_entry.delete(0, tk.END)

    except oracledb.DatabaseError as e:
        messagebox.showerror("Erro de Banco de Dados", f"Erro ao inserir fornecedor: {e}")
    finally:
        if connection:
            connection.close()

# Criar a janela principal
root = tk.Tk()
root.title("Cadastro de Fornecedores")

# Botão para criar a tabela (executar uma vez)
create_table_button = tk.Button(root, text="Criar Tabela", command=create_table)
create_table_button.grid(row=0, column=0, columnspan=2)

# Criar os campos de entrada e rótulos
tk.Label(root, text="Nome:").grid(row=1, column=0)
nome_entry = tk.Entry(root)
nome_entry.grid(row=1, column=1)

tk.Label(root, text="Descrição:").grid(row=2, column=0)
descricao_entry = tk.Entry(root)
descricao_entry.grid(row=2, column=1)

tk.Label(root, text="Setor:").grid(row=3, column=0)
setor_entry = tk.Entry(root)
setor_entry.grid(row=3, column=1)

tk.Label(root, text="Endereço:").grid(row=4, column=0)
endereco_entry = tk.Entry(root)
endereco_entry.grid(row=4, column=1)

tk.Label(root, text="Telefone:").grid(row=5, column=0)
telefone_entry = tk.Entry(root)
telefone_entry.grid(row=5, column=1)

tk.Label(root, text="Email:").grid(row=6, column=0)
email_entry = tk.Entry(root)
email_entry.grid(row=6, column=1)

tk.Label(root, text="Site:").grid(row=7, column=0)
site_entry = tk.Entry(root)
site_entry.grid(row=7, column=1)

# Botão para cadastrar fornecedor
cadastrar_button = tk.Button(root, text="Cadastrar", command=insert_supplier)
cadastrar_button.grid(row=8, column=0, columnspan=2)

root.mainloop()
